# Generated by Django 5.1.1 on 2024-09-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='images/Pizza-3007395.jpg', upload_to='images'),
        ),
    ]
