# Generated by Django 5.1.1 on 2024-09-11 09:45

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutaddress',
            name='country',
            field=django_countries.fields.CountryField(default='US', max_length=2),
        ),
    ]
