# Generated by Django 5.1.1 on 2024-09-13 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
